from selenium.webdriver.common.by import By

class BookeffortPage():
    sidemenu_bookeffort_x="//p[.='Book effort']"
    headline_bookeffort_x="//h2[@class='navbar_title text-ellipsis ew-mx-450']"
    label_my_effort_x="//label[@for='value3']"
    search_bar_x="//input[@id='md-input-c8fm4y0o']"
    label_searchHere_x="//label[@for='md-input-c8fm4y0o']"
    img_filtericon_x="//img[@class='cursor-pointer filter_icon']"
    img_arrowicon_x="//div[@class='md-button-content']//img[@class='mr-1']"
    dd_excel_x="//ul/li[1]//span[.='To Excel']"
    dd_pdf_x="//ul/li[2]//span[.='To PDF']"
    img_downarrow_x="(//img[@class='ml-1 downIcon'])[2]"
    label_export_x="//div[contains(text(),'Export')]"
    img_fr_arrow_x="//button[@class='md-button md-fab md-theme-default']//div[@class='md-ripple']//img"
    img_next_arrowbtn_x="//div[@class='btnNext']"
    label_thisweek_x="//p[@class='mb-0 ml-1']"
    label_statusName_x="//p[@class='statusName mb-0 mr-15']"
    label_selectDate_x="//label[@for='normalDatePicker']"
    btn_closeDate_x="//img[@class='close_icon cursor-pointer']"
    txt_selDate_x="//input[@role='text']"
    label_project_x="//span[@class='multiselect__placeholder']"
    dd_selArrow_project_x="//div[@class='multiselect__select']"
    label_task_x="//label[@for='task']"
    seltxt_task_x="//input[@id='md-input-dzqf9qk2g']"
    label_effort_x="//label[.='Effort']"
    img_clock_x="//i[contains(@class,'md-icon')]"
    txt_description_x="//textarea[@id='md-textarea-oprljuyw']"
    btn_addEffort_x="//div[contains(text(),'Add Effort')]"